<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211103175853 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $currentDate = date("Y-m-d H:m:s");
        $this->addSql("INSERT INTO field_offices (name, region_id ,created_at) VALUES "
            . "('Quezon City Parole And Probation Office No. 1', 1, '{$currentDate}'),"
            . "('Quezon City Parole And Probation Office No. 2', 1, '{$currentDate}'),"
            . "('Manila City Parole And Probation Office No. 3', 1, '{$currentDate}'),"
            . "('Manila City Parole And Probation Office No. 6', 1, '{$currentDate}'),"
            . "('Baybay City Parole And Probation Office', 12, '{$currentDate}'),"
            . "('Calbayog City Parole And Probation Office', 12, '{$currentDate}'),"
            . "('Maasin City Parole And Probation Office', 12, '{$currentDate}'),"
            . "('Ormoc City Parole And Probation Office', 12, '{$currentDate}'),"
            . "('Tacloban City Parole And Probation Office', 12, '{$currentDate}'),"
            . "('Biliran Parole And Probation Office', 12, '{$currentDate}'),"
            . "('Eastern Samar Parole And Probation Office', 12, '{$currentDate}'),"
            . "('Leyte Parole And Probation Office', 12, '{$currentDate}'),"
            . "('Northern Samar Parole And Probation Office No', 12,'{$currentDate}'),"
            . "('Samar Parole And Probation Office', 12, '{$currentDate}'),"
            . "('Southern Leyte Parole And Probation Office', 12, '{$currentDate}'),"
            . "('Cotabato City Parole And Probation Office', 11, '{$currentDate}'),"
            . "('General Santos City Parole And Probation Office', 11, '{$currentDate}'),"
            . "('Kidapawan City Parole And Probation Office', 11, '{$currentDate}'),"
            . "('Koronadal City Parole And Probation Office', 11, '{$currentDate}'),"
            . "('Marawi City Parole And Probation Office', 11, '{$currentDate}'),"
            . "('Tacurong City Parole And Probation Office', 11, '{$currentDate}'),"
            . "('Lanao Del Sur Parole And Probation Office', 11, '{$currentDate}'),"
            . "('Maguindanao Parole And Probation Office', 11, '{$currentDate}'),"
            . "('North Cotabato Parole And Probation Office', 11, '{$currentDate}'),"
            . "('Sarangani Parole And Probation Office', 11, '{$currentDate}'),"
            . "('South Cotabato Parole And Probation Office', 11, '{$currentDate}'),"
            . "('Sultan Kudarat Parole And Probation Office', 11, '{$currentDate}'),"
            . "('Iriga City Parole And Probation Office', 8, '{$currentDate}'),"
            . "('Legaspi City Parole And Probation Office', 8, '{$currentDate}'),"
            . "('Ligao City Parole And Probation Office', 8, '{$currentDate}'),"
            . "('Masbate City Parole And Probation Office', 8, '{$currentDate}'),"
            . "('Naga City Parole And Probation Office', 8, '{$currentDate}'),"
            . "('Sorsogon City Parole And Probation Office', 8, '{$currentDate}'),"
            . "('Tabaco City Parole And Probation Office', 8, '{$currentDate}'),"
            . "('Albay Parole And Probation Office', 8, '{$currentDate}'),"
            . "('Camarines Norte Parole And Probation Office', 8, '{$currentDate}'),"
            . "('Camarines Sur Parole And Probation Office No. 1', 8, '{$currentDate}'),"
            . "('Camarines Sur Parole And Probation Office No. 2', 8, '{$currentDate}'),"
            . "('Catanduanes Parole And Probation Office', 8, '{$currentDate}'),"
            . "('Masbate Province Parole And Probation Office', 8, '{$currentDate}'),"
            . "('Sorsogon Province Parole And Probation Office', 8, '{$currentDate}'),"
            . "('Cauayan City Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Ilagan City Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Santiago City Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Tuguegarao City Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Cagayan Parole And Probation Office No. 1', 2, '{$currentDate}'),"
            . "('Cagayan Parole And Probation Office No. 2', 2, '{$currentDate}'),"
            . "('Isabela Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Nueva Vizcaya Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Quirino Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Calapan City Parole And Probation Office', 7, '{$currentDate}'),"
            . "('Puerto Princesa City Parole And Probation Office', 7, '{$currentDate}'),"
            . "('Marinduque Parole And Probation Office', 7, '{$currentDate}'),"
            . "('Occidental Mindoro Parole And Probation Office', 7, '{$currentDate}'),"
            . "('Oriental Mindoro Parole And Probation Office', 7, '{$currentDate}'),"
            . "('Palawan Parole And Probation Office No. 1', 7, '{$currentDate}'),"
            . "('Palawan Parole And Probation Office No. 2', 7, '{$currentDate}'),"
            . "('Romblon Parole And Probation Office', 7, '{$currentDate}'),"
            . "('Bacolod City Parole And Probation Office No. 1', 9, '{$currentDate}'),"
            . "('Bacolod City Parole And Probation Office No. 2', 9, '{$currentDate}'),"
            . "('Bago City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Cadiz City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Escalante City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Himamaylan City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Iloilo City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Kabankalan City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('La Carlota City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Passi City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Roxas City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Sagay City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('San Carlos City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Silay City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Sipalay City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Talisay City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Victorias City Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Aklan Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Antique Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Capiz Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Guimaras Parole And Probation Office', 9, '{$currentDate}'),"
            . "('Iloilo Province Parole And Probation Office No. 1', 9, '{$currentDate}'),"
            . "('Iloilo Province Parole And Probation Office No. 2', 9, '{$currentDate}'),"
            . "('Iloilo Province Parole And Probation Office No. 3', 9, '{$currentDate}'),"
            . "('Baguio City Parole And Probation Office', 3, '{$currentDate}'),"
            . "('Abra Parole And Probation Office', 3, '{$currentDate}'),"
            . "('Apayao Parole And Probation Office', 3, '{$currentDate}'),"
            . "('Benguet Parole And Probation Office', 3, '{$currentDate}'),"
            . "('Ifugao Parole And Probation Office', 3, '{$currentDate}'),"
            . "('Kalinga Parole And Probation Office', 3, '{$currentDate}'),"
            . "('Mt. Province Parole And Probation Office', 3, '{$currentDate}'),"
            . "('Dapitan City Parole And Probation Office', 13, '{$currentDate}'),"
            . "('Dipolog City Parole And Probation Office', 13, '{$currentDate}'),"
            . "('Pagadian City Parole And Probation Office', 13, '{$currentDate}'),"
            . "('Zamboanga City Parole And Probation Office No. 1', 13, '{$currentDate}'),"
            . "('Zamboanga City Parole And Probation Office No. 2', 13, '{$currentDate}'),"
            . "('Sulu Parole And Probation Office', 13, '{$currentDate}'),"
            . "('Zamboanga Del Sur Parole And Probation Office No. 1', 13, '{$currentDate}'),"
            . "('Zamboanga Del Sur Parole And Probation Office No. 2', 13, '{$currentDate}'),"
            . "('Zamboanga Sibugay Parole And Probation Office', 13, '{$currentDate}'),"
            . "('Zamboanga Del Norte Parole And Probation Office', 13, '{$currentDate}'),"
            . "('Cagayan De Oro City Parole And Probation Office', 14, '{$currentDate}'),"
            . "('Gingoog City Parole And Probation Office', 14, '{$currentDate}'),"
            . "('Iligan City Parole And Probation Office', 14, '{$currentDate}'),"
            . "('Malaybalay City Parole And Probation Office', 14, '{$currentDate}'),"
            . "('Oroquieta City Parole And Probation Office', 14, '{$currentDate}'),"
            . "('Tangub City Parole And Probation Office', 14, '{$currentDate}'),"
            . "('Valencia City Parole And Probation Office', 14, '{$currentDate}'),"
            . "('Bukidnon Parole And Probation Office No. 1', 14, '{$currentDate}'),"
            . "('Bukidnon Parole And Probation Office No. 2', 14, '{$currentDate}'),"
            . "('Camiguin Parole And Probation Office', 14, '{$currentDate}'),"
            . "('Lanao Del Norte Parole And Probation Office', 14, '{$currentDate}'),"
            . "('Misamis Occidental Parole And Probation Office', 14, '{$currentDate}'),"
            . "('Misamis Oriental Parole And Probation Office', 14, '{$currentDate}'),"
            . "('Ozamiz City Parole And Probation Office', 14, '{$currentDate}'),"
            . "('Alaminos City Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Candon City Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Dagupan City Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Laoag City Parole And Probation Office', 2, '{$currentDate}'),"
            . "('San Fernando City Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Urdaneta City Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Vigan City/Ilocos Sur Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Ilocos Norte Parole And Probation Office', 2, '{$currentDate}'),"
            . "('La Union Province Parole And Probation Office', 2, '{$currentDate}'),"
            . "('Pangasinan Parole And Probation Office No. 1', 2, '{$currentDate}'),"
            . "('Pangasinan Parole And Probation Office No. 2', 2, '{$currentDate}'),"
            . "('Bislig City Parole And Probation Office', 15, '{$currentDate}'),"
            . "('Butuan City Parole And Probation Office', 15, '{$currentDate}'),"
            . "('Surigao City Parole And Probation Office', 15, '{$currentDate}'),"
            . "('Tandag City Parole And Probation Office', 15, '{$currentDate}'),"
            . "('Agusan Del Norte Parole And Probation Office', 15, '{$currentDate}'),"
            . "('Agusan Del Sur Parole And Probation Office', 15, '{$currentDate}'),"
            . "('Surigao Del Norte Parole And Probation Office No. 1', 15, '{$currentDate}'),"
            . "('Surigao Del Norte Parole And Probation Office No. 2', 15, '{$currentDate}'),"
            . "('Surigao Del Sur Parole And Probation Office', 15, '{$currentDate}'),"

            . "('', 1, '{$currentDate}'),"
            . "('', 1, '{$currentDate}')");
    }

    public function down(Schema $schema): void
    {
        $this->addSql("TRUNCATE TABLE field_offices");
    }

    public function isTransactional(): bool
    {
        return false;
    }
}
