user_index:
    path: /api/user
    controller: App\Controller\UserController::index
    methods: GET

login:
    path: /api/login
    methods: POST
    defaults:
        _format: json

register:
    path: /api/register
    controller: App\Controller\UserController::register
    methods: POST