user_index:
    path: /api/user
    controller: App\Controller\UserController::index
    methods: GET

login:
    path: /api/login
#    controller: App\Controller\UserController::authenticate
    methods: POST
    defaults:
        _format: json
